### ISSUE TITLE
IE11 Compatibility

### ISSUE THREAD

**Issue by rafaelytakei** [trevorr/tsfv#4]
Hi, is there some way to make this lib IE11 compatible? I'm currently using it on a new project which requires IE11 support, but I couldn't make it work with babel

**Comment by trevorr** [comment]
I just pushed version 1.0.2, which includes a SystemJS ES5 build for browsers as old as IE 10. You may need to tell your bundler to use the `browser` entrypoint instead of `main`. More info here: https://2ality.com/2017/04/setting-up-multi-platform-packages.html

I don't have an easy way to test IE 11 myself, so please let me know how it goes.

**Comment by rafaelytakei** [comment]
Hey, thanks for the fast answer! I still couldn't get it to work, I'm currently using webpack, so it ends up defaulting to browser instead of main already.

Before your push, I was getting an error because there was a `class` on the code, which wasn't supported by IE11, but now that seems to be fine. However, now I'm getting the following error:

`SCRIPT5007: Object expected`
which redirects to [this](https://i.imgur.com/kcapaSn.png) part of the code (the `void 0` in the 5th line). 

I'm not very used to reporting things like this, so I'm not even sure if the image helps, but if you need anything else just let me know! Thanks again!

**Comment by trevorr** [comment]
I think that's the SystemJS module registration. You probably need to include the [SystemJS minimal loader](https://github.com/systemjs/systemjs#1-sjs-minimal-loader) in your build.

Background: To output a single file for browser use, I needed to use AMD or SystemJS. I chose the latter because it can be used [universally](https://auth0.com/blog/javascript-module-systems-showdown/#The-All-in-One-Solution--System-js).

Regarding Webpack, this may be helpful: https://github.com/systemjs/systemjs#compatibility-with-webpack
